### ISSUE TITLE
How to generate histogram of latency or throughput?

### ISSUE THREAD

**Issue by flplv** [plasma-umass/coz#108]
Current visualization tools only show the optimization impact, what about showing raw durations as histograms? So that I can infer the quality of the generated data?
Nice work, by the way.

**Comment by ccurtsinger** [comment]
A histogram of latencies/throughputs would be useful, but coz is only able to track averages over time. That's because throughput is counted as visits / time, and latency is calculated using Little's law. Of course coz checks these averages regularly, so you could probably use the data in the profiler output to plot a histogram of averages over short time periods, but given that experiments are happening during these periods it's unclear how meaningful those data would be.

Did you have a specific scenario in mind where this would be useful?

**Comment by ccurtsinger** [comment]
I haven't heard back, so I'll close this for now. Feel free to reopen the issue if you have some more details about your request.
