### ISSUE TITLE
Coz just outputs two lines per benchmark

### ISSUE THREAD

**Issue by BourgondAries** [plasma-umass/coz#109]
I run `make bench` inside the `benchmarks/kmeans` directory and get just this in `profile.coz`:
```
startup	time=1568731888530442258
runtime	time=1000760853
```
I don't think I can do anything with this, and the guide says I need to do multiple runs, so I did (300 runs), and each run just adds two lines like that and nothing more.

This is on Manjaro 18.1.0, kernel 5.3.0-1, using GCC v9.1.0, as well as GCC v8.3.0, with the latest libelfin/libdwarf from github (ref ac45a09).

Is it supposed to output just this? What do I do with this?

**Comment by emeryberger** [comment]
Nope. It sounds like the progress points are not being executed / built for some reason.

**Comment by philipc** [comment]
I'm seeing the same issue, and it looks like the problem is that `get_loaded_files` doesn't account for the executable segment offset of 0x1000, which you can see with `readelf -l`:
```
  Type           Offset             VirtAddr           PhysAddr
                 FileSiz            MemSiz              Flags  Align
  LOAD           0x0000000000001000 0x0000000000001000 0x0000000000001000
                 0x0000000000000fbd 0x0000000000000fbd  R E    0x1000
```

If I add this hack then it works better:
```
@@ -246,7 +246,7 @@ unordered_map<string, uintptr_t> get_loaded_files() {
 
     // If this is an executable mapping of an absolute path, include it
     if(perms[2] == 'x' && path[0] == '/') {
-      result[path] = base;
+      result[path] = base - 0x1000;
     }
   }
```

It looks like this is running in the process being profiled, so maybe it should use `dl_iterate_phdrs` instead of `/proc/self/maps`? Although there is an issue to run in a separate process: #60

**Comment by ccurtsinger** [comment]
Hopefully #132 fixes this issue. My development environment does not produce executables that are loaded with an offset, so I have not been able to test that case. If you could check it (or describe how you produced such an executable) I'd appreciate it.

I used to use `dl_iterate_phdr`, but switched away because of some issue I have now completely forgotten. That may be more reliable so I'll give it a try at some point.

**Comment by jesperpedersen** [comment]
Looks like linking problems too

```
[jpedersen@localhost libcoz]$ ldd ./libcoz.so 
	linux-vdso.so.1 (0x00007ffeb151a000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007f70e342c000)
	librt.so.1 => /lib64/librt.so.1 (0x00007f70e3422000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f70e3401000)
	libelf++.so.0 => not found
	libdwarf++.so.0 => not found
	libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007f70e3207000)
	libm.so.6 => /lib64/libm.so.6 (0x00007f70e30bf000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f70e30a5000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f70e2edf000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f70e34db000)
```
```
[jpedersen@localhost libcoz]$ locate libelf++.so
/usr/local/lib/libelf++.so
/usr/local/lib/libelf++.so.0
```

**Comment by philipc** [comment]
I was using clang version `6.0.0-1ubuntu2`, and #132 fixes it for that.

It still doesn't work if I use clang version `8.0.1-svn363027-1~exp1~20190611211629.77`, and the problem looks similar to what @jesperpedersen reports. I haven't tried to figure out what's different.

**Comment by jesperpedersen** [comment]
Turns out that libelfin 0.3 doesn't work; `line_info.file->path` is empty. Either use master branch, which has the fix (https://github.com/aclements/libelfin/commit/4a678c782847ac2db3a1c1790b1b666f804d1d4f) or the 0.2 release.

**Comment by jesperpedersen** [comment]
I think this issue can be closed unless a note should be added to the README.md file regarding the libelfin issue

**Comment by ccurtsinger** [comment]
Thanks for the diligent debugging!
