### ISSUE TITLE
sqlite patch mentioned in the paper

### ISSUE THREAD

**Issue by albertnetymk** [plasma-umass/coz#122]
Hello, I am quite amazed by the elegance of the fixes for sqlite. I wonder if such patch is accessible in public domain, some mailing list or ticket database. "We have submitted patches to the developers of all the applications we optimized." from the paper.

I went to sqlite ticket database, but can't find anything using the keyword "mutex".

**Comment by Radrik5** [comment]
Additional indirection is still there: https://github.com/mackyle/sqlite/blob/a419afd73a544e30df878db55f7faa17790c01bd/src/mutex_unix.c

I would be nice to know what sqlite devs think about the patch.

**Comment by albertnetymk** [comment]
I am curious as well, and I want to see the patch if accessible anywhere.

**Comment by ccurtsinger** [comment]
The problem with the SQLite patch is that it removes the option to configure SQLite's synchronization mode at compile time. The SQLite project could change their configuration options to use `#ifdef`s instead of the struct of function pointers referenced in the paper, but my change was much smaller than what would be required for the core project.

I am about to merge a pull request that includes the other patches.
